---
name: Publish to Ansible Galaxy

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    name: Build and Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Set up Python
        uses: actions/setup-python@v7
        with:
          python-version: '3.13'
          cache: 'pip'
          cache-dependency-path: .github/requirements-ci.txt

      - name: Install dependencies
        run: pip install -r .github/requirements-ci.txt

      - name: Build and publish to Galaxy
        run: |
          ansible-galaxy collection build
          ansible-galaxy collection publish *.tar.gz --api-key=${{ secrets.GALAXY_API_KEY }}
        env:
          ANSIBLE_GALAXY_API_KEY: ${{ secrets.GALAXY_API_KEY }}
